---
- name: Create new domain in a new forest on the target host and reboot
  microsoft.ad.domain:
    domain_netbios_name: "{{ domain_netbios_name }}"
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
  register: domain_install

- name: Reboot host if domain install requires it
  ansible.windows.win_reboot:
  when: domain_install.reboot_required

- name: Ensure deployment admin user is present
  microsoft.ad.user:
    identity: deploy_admin
    password: D3PL0YP@SSW0RD
    state: present
    groups:
      set:
      - Domain Admins
      - Domain Users

